### ISSUE TITLE
Fails when Device is offline when first added.

### ISSUE THREAD

**Issue by ZachBenz** [Ghawken/IndigoPlugin-iFindFriendMini#15]
If a device reports itself offline when first added, and thus the latitude and longitude are blank, then FindFriendsMini fails with an error:

```
   FindFriendsMini Error           Error Within checkHomeOther:
Traceback (most recent call last):
  File "plugin.py", line 1458, in checkHomeOther
    iDevLatitude = float(dev.states['latitude'])
ValueError: could not convert string to float: 
```

This causes GeoFences to fail to properly be updated (because the error gets thrown while trying to update GeoFence status).

**Comment by Ghawken** [comment]
Hi
Thanks - the exception is caught (just Indigo 7 logging - enables to show in great detail)  
So should continue to work and once online should be okay.

But will make a bit more tidy!

G

**Comment by ZachBenz** [comment]
Agreed, once online all will be good.  The problem is that if the device is offline from the start, and stays offline for some time, never going online, GeoFence updates are broken.

Thanks!

**Comment by Ghawken** [comment]
Thanks
Have updated to 0.5.8 which should fix this.
Should be there now.
G
