### ISSUE TITLE
myFriendDevices should use 'following', not 'followers'

### ISSUE THREAD

**Issue by ZachBenz** [Ghawken/IndigoPlugin-iFindFriendMini#16]
Currently in the `myFriendDevices` method in `plugin.py`, we iterate over the **'followers'** data in friends.data.  This means that if you set up an iCloud account to use with FindFriendsMini, and then have it follow other accounts that do not in turn follow back, then the 'followers' list will be empty!  As a result, you won't find any friends in the **targetFriend** drop down list when configuring the settings for a new FindFriends Device

Instead, we should iterate over the **'following'** data, and pull out the 'invitationAcceptedByEmail' for the human readable label ('id' is still the correct thing to pull from 'following' data).

This way the iCloud account only has to follow the other accounts we are interested in the location of, and not vice versa.

I will create a pull request with the two line patch to fix this issue.

**Comment by ZachBenz** [comment]
Pull request submitted (3 lines, not 2 :-) )

**Comment by Ghawken** [comment]
Hi
Do follow - and should just pull

Can you follow without being a follower - I thought is was both ways or nothing?

You can stop sharing location with individuals, but not sure can follow but not be a following - if follow?!?

**Comment by ZachBenz** [comment]
Yes, it can be one way. If you add a person (for example the special Indigo iCloud account you’ve created) in the Find Friends app on a person’s iOS device, the Indigo iCloud account becomes a follower and gets a notification to this effect. If you explicitly **do not** share the Indigo iCloud account’s location in return, it never becomes a follower. Thus, it is following, but not a follower.

**Comment by Ghawken** [comment]
Thanks
Merged.  Still not sure iFriendsApp lets you follow one way?.  But regardless if the data the same from both followers and following - you are correct this is the way to do it.
Just seen your reply
Thanks
G

**Comment by ZachBenz** [comment]
Thanks!!
