### ISSUE TITLE
Find my friends endpoint changed in May, 2023

### ISSUE THREAD

**Issue by gcobb321** [Ghawken/IndigoPlugin-iFindFriendMini#19]
Glenn,
You identified the new Friend my Friends endpoint which I used in iCloud3 in 2021. Apple made some changes in May, 2023 and that is no longer working. I’ve been doing a lot of searching to see if another web url is available to get the location of people who are sharing their location without success. 

I came across your name in an old iCloud3 forum and thought I would reach out to see if you are still involved in this project and might be a able to point to a solution. From what I can tell, the people sharing their location is tied to the contacts list. However, downloading the contacts from  the Apple account does not include any data regarding their shared status. 

I’ve rewritten iCloud3 (it’s still in beta) and hope to have this fixed before I release it. 

Thanks. 

Gary Cobb (iCloud3)

**Comment by Ghawken** [comment]
Hi Gary,
 
Yeah - the website for findfriends was deleted in 2021, and now in May 2023  the actual URL have been cancelled.  Initally returning the same data as FamilyDevices for about a week and now non-existent altogether.

I would guess they basically don’t exist anymore, as accessible via URL

Given pyicloud get its data through website url imitation - it would seem that this option is gone forever unfortunately.

One option may be to check Find iOS app data via a Proxy/Wire Shark and see what it pulls to get info.   This may expose friend again and/or the tag/devices data.   However would be a complete change of current practice and probably a reasonably big effort which then might die at apples whim.  I thought about it, but for reasons above haven’t tried….
